name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - id: "checkout"
        uses: "actions/checkout@v3"

      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-v1-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: create build
        run: yarn install

      - name: run unit tests
        run: yarn test --coverage
