name: Upload assets to Google Cloud Storage (Production)

on:
  push:
    branches:
      - main

jobs:
  upload_staging_assets_to_gcs:
    uses: ./.github/workflows/upload-to-gcs.yml
    with:
      environment: production
    secrets: inherit
